# Generated by Django 2.2.5 on 2019-09-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sector', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=15)),
                ('time_in', models.TimeField()),
                ('daytime_in', models.CharField(max_length=2)),
                ('time_out', models.TimeField()),
                ('daytime_out', models.CharField(max_length=2)),
                ('hours_code', models.CharField(max_length=4)),
                ('hours_worked', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
