# Generated by Django 2.2.5 on 2019-09-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('timeCard', '0002_auto_20190923_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='file_number',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
            preserve_default=False,
        ),
    ]
