# Generated by Django 2.2.5 on 2019-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0004_auto_20190927_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
