# Generated by Django 2.2.5 on 2019-09-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0007_auto_20190927_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='daytime_in',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='daytime_out',
        ),
        migrations.AlterField(
            model_name='timecard',
            name='hours_worked',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_in',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_out',
            field=models.CharField(max_length=10),
        ),
    ]
