# Generated by Django 2.2.5 on 2019-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0008_auto_20190928_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
