# Generated by Django 2.2.5 on 2019-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time_in', models.CharField(max_length=10)),
                ('time_out', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=5)),
                ('hours_code', models.CharField(max_length=4)),
                ('hours_worked', models.TimeField()),
            ],
        ),
    ]
