<<<<<<< Updated upstream
# Generated by Django 2.2.5 on 2019-09-27 17:42
=======
# Generated by Django 2.2.5 on 2019-09-27 19:46
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
