# Generated by Django 2.2.5 on 2019-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angularapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_name',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
