# Generated by Django 2.2.5 on 2019-09-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angularapi', '0002_auto_20190923_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='file_number',
        ),
    ]
