# Generated by Django 2.2.5 on 2019-09-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angularapi', '0003_auto_20190924_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='first_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_Name',
            field=models.CharField(max_length=100),
        ),
    ]
