# Generated by Django 2.2.5 on 2019-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('file_number', models.PositiveIntegerField()),
                ('pay_roll', models.CharField(max_length=3)),
            ],
        ),
    ]
