<<<<<<< Updated upstream
# Generated by Django 2.2.5 on 2019-09-26 15:49
=======
# Generated by Django 2.2.5 on 2019-09-27 19:46
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='file_number',
        ),
    ]
