# Generated by Django 2.2.5 on 2019-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pay_roll',
            field=models.CharField(max_length=4),
        ),
    ]
